apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: jicowan/aws-secrets-manager
  local:
    push: true
    useBuildkit: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: default
    build:
      local:
        push: true
